#ifndef PROTOCOL_H
#define PROTOCOL_H
//消息协议（结构体）

enum ENUM_MSG_TYPE{//消息类型枚举值
    ENUM_MSG_TYPE_MIN =0,

    ENUM_MSG_TYPE_REGIST_REQUEST,//1
    ENUM_MSG_TYPE_REGIST_RESPOND,//2
    ENUM_MSG_TYPE_LOGIN_REQUEST,//3
    ENUM_MSG_TYPE_LOGIN_RESPOND,//4
    ENUM_MSG_TYPE_FIND_USER_REQUEST,
    ENUM_MSG_TYPE_FIND_USER_RESPOND,
    ENUM_MSG_TYPE_ONLINE_USER_REQUEST,
    ENUM_MSG_TYPE_ONLINE_USER_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_ARGEE_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_ARGEE_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FRIEND_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FRIEND_RESPOND,
    ENUM_MSG_TYPE_DEL_FRIEND_REQUEST,
    ENUM_MSG_TYPE_DEL_FRIEND_RESPOND,
    ENUM_MSG_TYPE_CHAT_REQUEST,
    ENUM_MSG_TYPE_CHAT_RESPOND,
    ENUM_MSG_TYPE_MKDIR_REQUEST,
    ENUM_MSG_TYPE_MKDIR_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FILE_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FILE_RESPOND,
    ENUM_MSG_TYPE_DEL_DIR_REQUEST,
    ENUM_MSG_TYPE_DEL_DIR_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_ARGEE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_ARGEE_RESPOND,


    ENUM_MSG_TYPE_MAX=0x00ffffff
};

struct FileInfo{
    char caName[32];
    int iFileType;
};

struct PDU{//协议数据单元
    unsigned int uiPDULen;//总长
    unsigned int uiMsgLen;//（柔性数组）消息长度=总长-结构体长度
    unsigned int uiMsgType;//类型
    char caData[64];//参数
    char caMsg[];//实际消息
};

PDU* mkPDU(unsigned int uiMsgLen=0);//根据消息长度申请空间，默认为0


#endif // PROTOCOL_H
